inveniosoftware/invenio-administration

.eslintrc.yml, .github/workflows/tests.yml, MANIFEST.in, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchEmptyResults.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchFacets.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchLayout.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultGridItem.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultItem.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResults.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/index.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/search.js, run-js-linter.sh
closes https://github.com/inveniosoftware/invenio-administration/issues/1
=> linter: implement eslint and add pipeline step

invenio_administration/assets/semantic-ui/js/invenio_administration/theme.js, invenio_administration/config.py, invenio_administration/templates/semantic-ui/invenio_administration/base.html, invenio_administration/templates/semantic-ui/invenio_administration/header.html, invenio_administration/templates/semantic-ui/invenio_administration/header_login.html, invenio_administration/webpack.py
closes https://github.com/inveniosoftware/invenio-administration/issues/2
needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1823
=> back office: add top navigation

.gitignore, MANIFEST.in, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchBarElement.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchEmptyResults.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResults.js, invenio_administration/assets/semantic-ui/translations/invenio_administration/i18next-scanner.config.js, invenio_administration/assets/semantic-ui/translations/invenio_administration/i18next.js, invenio_administration/assets/semantic-ui/translations/invenio_administration/messages/de/translations.json, invenio_administration/assets/semantic-ui/translations/invenio_administration/messages/el/translations.json, invenio_administration/assets/semantic-ui/translations/invenio_administration/messages/en/translations.json, invenio_administration/assets/semantic-ui/translations/invenio_administration/messages/es/translations.json, invenio_administration/assets/semantic-ui/translations/invenio_administration/messages/index.js, invenio_administration/assets/semantic-ui/translations/invenio_administration/package-lock.json, invenio_administration/assets/semantic-ui/translations/invenio_administration/package.json, invenio_administration/assets/semantic-ui/translations/invenio_administration/scripts/compileCatalog.js, invenio_administration/assets/semantic-ui/translations/invenio_administration/scripts/initCatalog.js, invenio_administration/assets/semantic-ui/translations/invenio_administration/translations.pot
Closes https://github.com/inveniosoftware/invenio-administration/issues/17
- Adds js translations (`i18next`)
=> translations: add js translations

invenio_administration/menu/menu.py, invenio_administration/templates/semantic-ui/invenio_administration/details.html, invenio_administration/templates/semantic-ui/invenio_administration/search.html, invenio_administration/views/base.py
=> backend: added details view backend

invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchBarElement.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultItem.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultOptions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultsContainer.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/search.js, invenio_administration/templates/semantic-ui/invenio_administration/search.html, invenio_administration/views/base.py
closes https://github.com/inveniosoftware/invenio-administration/issues/6
=> list view: further implement the list view

invenio_administration/admin.py, invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Actions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Create.js, invenio_administration/assets/semantic-ui/js/invenio_administration/actions/CustomResourceActions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Delete.js, invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Edit.js, invenio_administration/assets/semantic-ui/js/invenio_administration/actions/index.js, invenio_administration/assets/semantic-ui/js/invenio_administration/api/actions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/api/config.js, invenio_administration/assets/semantic-ui/js/invenio_administration/api/routes.js, invenio_administration/assets/semantic-ui/js/invenio_administration/routes.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultItem.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultOptions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultsContainer.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/search.js, invenio_administration/errors.py, invenio_administration/templates/semantic-ui/invenio_administration/base.html, invenio_administration/templates/semantic-ui/invenio_administration/header/header.html, invenio_administration/templates/semantic-ui/invenio_administration/search.html, invenio_administration/views/base.py, invenio_administration/views/dashboard.py
=> Administration: delete action

tests/mock_module/administration/mock.py, tests/test_base.py
closes https://github.com/inveniosoftware/invenio-administration/issues/31
=> tests: added view url tests

invenio_administration/menu/menu.py
* closes https://github.com/inveniosoftware/invenio-administration/issues/44
=> menu: sort alphatebically by category

invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchBarElement.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/search.js
Fixes an issue with search bar that is currently not displaying any character until a key is pressed.
Additionally, the query state is only updated one letter at the time.
This PR fixes both issues.
=> Search bar does not update its input

invenio_administration/assets/semantic-ui/js/invenio_administration/actions/ActionsDropdown.js, invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Delete.js, invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Edit.js, invenio_administration/assets/semantic-ui/js/invenio_administration/api/serializers.js, invenio_administration/assets/semantic-ui/js/invenio_administration/components/index.js, invenio_administration/assets/semantic-ui/js/invenio_administration/create/CreatePage.js, invenio_administration/assets/semantic-ui/js/invenio_administration/create/index.js, invenio_administration/assets/semantic-ui/js/invenio_administration/details/ActionModal.js, invenio_administration/assets/semantic-ui/js/invenio_administration/details/AdminDetailsView.js, invenio_administration/assets/semantic-ui/js/invenio_administration/details/DetailsComponent.js, invenio_administration/assets/semantic-ui/js/invenio_administration/details/index.js, invenio_administration/assets/semantic-ui/js/invenio_administration/edit/EditPage.js, invenio_administration/assets/semantic-ui/js/invenio_administration/edit/index.js, invenio_administration/assets/semantic-ui/js/invenio_administration/formik/AdminForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/formik/GenerateForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultsContainer.js, invenio_administration/templates/semantic-ui/invenio_administration/base.html, invenio_administration/templates/semantic-ui/invenio_administration/create.html, invenio_administration/templates/semantic-ui/invenio_administration/details.html, invenio_administration/templates/semantic-ui/invenio_administration/edit.html, invenio_administration/templates/semantic-ui/invenio_administration/search.html, invenio_administration/templates/semantic-ui/invenio_administration/sidebar/sidenav.html, invenio_administration/views/base.py, invenio_administration/views/dashboard.py, invenio_administration/webpack.py
Closes https://github.com/inveniosoftware/invenio-administration/issues/18
- Adds details page layout as in mockup
=> details: Add details page UI

invenio_administration/assets/semantic-ui/js/invenio_administration/search/search.js
=> List view: mimic invenio-app-rdm facets Requires [https://github.com/inveniosoftware/invenio-search-ui/pull/162]

invenio_administration/templates/semantic-ui/invenio_administration/create.html, invenio_administration/templates/semantic-ui/invenio_administration/details.html, invenio_administration/templates/semantic-ui/invenio_administration/edit.html, invenio_administration/templates/semantic-ui/invenio_administration/macros.html, invenio_administration/templates/semantic-ui/invenio_administration/search.html
=> Administration: add go back button in create edit and details

invenio_administration/admin.py, invenio_administration/menu/menu.py, invenio_administration/templates/semantic-ui/invenio_administration/header/header_login.html
* closes: #66
Admin:
Not admin:
=> Administration: add admin link in the profile menu

invenio_administration/assets/semantic-ui/js/invenio_administration/actions/DeleteModalTrigger.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/Actions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/search.js
* Add option to disable action buttons
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1037
=> search: export default components

invenio_administration/menu/menu.py
=> Sidebar: highlight sidebar menus when children pages are visible

invenio_administration/templates/semantic-ui/invenio_administration/header/header_login.html
closes: #61
requires: inveniosoftware/invenio-rdm-records#1044 https://github.com/inveniosoftware/invenio-theme/pull/314
=> Administration menu: add a create oai-pmh set menu entry [REQUIRES inveniosoftware/invenio-theme#314]

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModal.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/components/utils.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/ActionForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/ui_messages/messages.js
closes https://github.com/inveniosoftware/invenio-administration/issues/84
=> forms: reset error state after message dismiss.

invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchBarElement.js
=> Sort options: fix sort option disappear after search

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModal.js
* closes https://github.com/inveniosoftware/invenio-administration/issues/71
=> deleteModal: Make modal overridable

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModal.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModalTrigger.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchBarElement.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchEmptyResults.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/ui_messages/messages.js, invenio_administration/templates/semantic-ui/invenio_administration/base.html, invenio_administration/templates/semantic-ui/invenio_administration/create.html, invenio_administration/templates/semantic-ui/invenio_administration/edit.html, invenio_administration/templates/semantic-ui/invenio_administration/header/header.html, invenio_administration/templates/semantic-ui/invenio_administration/header/header_login.html, invenio_administration/templates/semantic-ui/invenio_administration/macros.html, invenio_administration/templates/semantic-ui/invenio_administration/search.html, invenio_administration/templates/semantic-ui/invenio_administration/sidebar/sidenav.html
Closes https://github.com/inveniosoftware/invenio-administration/issues/75
Adds...
- `aria-label` to icon-buttons and search input
- `aria-hidden` for icons and dividers 
- a11y functionality to modals (focus cancel button on opening)
- alert role to messages
- `<h2>` for headings in side menu
=> accessibility: improve overall a11y

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModalTrigger.js
Closes https://github.com/inveniosoftware/invenio-administration/issues/112
=> accessibility: remove hardcoded aria-expanded from modal trigger

invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResultItem.js
Closes https://github.com/inveniosoftware/invenio-administration/issues/109
Adds `word-break-all` class to table cell.
Needs https://github.com/inveniosoftware/invenio-theme/pull/328
=> search result item: add word-break-all class to table cell

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/Actions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModalTrigger.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/details/AdminDetailsView.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResultItem.js
* closes https://github.com/inveniosoftware/invenio-administration/issues/106
=> actions: add popup to disabled buttons

invenio_administration/assets/semantic-ui/js/invenio_administration/src/details/AdminDetailsView.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/details/index.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1081
=> Add popup details view

invenio_administration/templates/semantic-ui/invenio_administration/index.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1901
=> dashboard: update welcome message

invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/ActionForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js
=> Create/edit forms: remove cancel button

invenio_administration/generators.py, invenio_administration/permissions.py, invenio_administration/views/base.py, setup.cfg
* closes https://github.com/inveniosoftware/invenio-administration/issues/128
=> permissions: add administration permission

invenio_administration/assets/semantic-ui/js/invenio_administration/src/components/utils.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/GenerateForm.js
* closes: inveniosoftware/invenio-rdm-records#1092
=> OAI-PMH: Improve labelling

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/ResourceActions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/ActionForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/GenerateForm.js
Closes https://github.com/inveniosoftware/invenio-administration/issues/149
Needs PR https://github.com/inveniosoftware/invenio-communities/pull/860
- Adds placeholder and description to date input
- Removes underscore from input label
- Fixes spacing bugs for modal actions
Discussed irl: the DatePicker will be added at a later point. See my comment on the task for details.
=> action form: fix styling issue and date input field

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/Delete.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2042
=> deleteCmp: fix popup display

CHANGES.rst, invenio_administration/__init__.py
=> release: v1.0.6

invenio_administration/assets/semantic-ui/js/invenio_administration/src/components/Formatter.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/details/DetailsComponent.js
Align top first column content of the details view
closes: inveniosoftware/invenio-pages#66
=> Administration: allow pre-formatted input in details view

CHANGES.rst, invenio_administration/__init__.py, setup.cfg
=> release: v1.2.0

invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResults.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162
=> translations: fix string concatenation and pluralization

invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/ActionForm.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/54
=> assets: fix action form display

CHANGES.rst, invenio_administration/__init__.py
=> release: v1.6.0

CHANGES.rst, invenio_administration/__init__.py, invenio_administration/marshmallow_utils.py
=> marsmallow_utils: ignore Method field from jsonify

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/Actions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/details/AdminDetailsView.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResultItem.js, invenio_administration/marshmallow_utils.py, invenio_administration/views/base.py
assets: flexible admin action buttons styling
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2408
=> views: adapt actions creation

CHANGES.rst, invenio_administration/__init__.py
=> release: v1.9.0

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/ResourceActions.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/details/AdminDetailsView.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResultItem.js, invenio_administration/marshmallow_utils.py
* styling: improve action buttons
* closes https://github.com/inveniosoftware/invenio-communities/issues/1006
=> assets: add error handling to action details view

invenio_administration/assets/semantic-ui/js/invenio_administration/src/components/BoolFormatter.js
Partially Closes [#375](https://github.com/zenodo/rdm-project/issues/375)
**Reminder**
2. You agree that …
=> ui: added tooltip for icons

CHANGES.rst, invenio_administration/__init__.py, invenio_administration/marshmallow_utils.py
* Closes https://github.com/zenodo/rdm-project/issues/491
=> Add URL mapping and release v1.9.3

invenio_administration/marshmallow_utils.py
* closes https://github.com/zenodo/rdm-project/issues/558
=> schema: support EDTFDateTimeString format

CHANGES.rst, invenio_administration/__init__.py
=> release: v1.10.1

invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/GenerateForm.js, invenio_administration/marshmallow_utils.py
Closes Issue [#196](https://github.com/inveniosoftware/invenio-administration/issues/196)
**Reminder** …
=> form: replaced text area with richinput editor

invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/Actions.js
- Closes https://github.com/zenodo/ops/issues/373
=> actions: add explicit prop for dropdown display

invenio_administration/marshmallow_utils.py
Add support for the [marshmallow `Enum` field](https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Enum) which was added in 3.18.0
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository- …
=> marshmallow_utils: add enum to mapping

CHANGES.rst, invenio_administration/__init__.py, setup.cfg
- bump `invenio-records-resources` and `invenio-vocabularies` to new majors.
- UI fixed for administration views
=> release: v2.3.0

invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResults.js
close https://github.com/inveniosoftware/invenio-app-rdm/issues/2051
before
after
**Frontend**
**Reminder**
1. You license your contribution under the same terms as …
=> ui: add comma separator to admin result count

invenio_administration/assets/semantic-ui/js/invenio_administration/package.json, invenio_administration/webpack.py
* closes https://github.com/zenodo/rdm-project/issues/657
=> package: bump react-invenio-forms

invenio_administration/config.py, invenio_administration/templates/semantic-ui/invenio_administration/base.html
* display configured packages version at the bottom of the side bar
* closes inveniosoftware/invenio-app-rdm#2838
=> feat: display packages versions in the side bar

invenio_administration/assets/semantic-ui/js/invenio_administration/src/details/details.js
- Fixes `SyntaxError: name is not valid JSON`
as name is a string e.g "User details"
**Frontend**
**Reminder**
2. You …
=> details: remove parsing for name field

invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResults.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/198
=> records search: render Mathjax in the results list

invenio_administration/assets/semantic-ui/js/invenio_administration/package.json
* closes https://github.com/inveniosoftware/react-searchkit/issues/278
=> dependencies: update axios

invenio_administration/views/base.py
Close [#2899](https://github.com/inveniosoftware/invenio-app-rdm/issues/2899)
Setting default_size and pagination_options as changing in invenio-search-ui would change it everywhere including non-admin pages
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
=> admin: change default # of results from 10 to 20

invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/fields/fields.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/329
=> ui: handle date values in the forms

invenio_administration/admin.py, invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModal.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/ActionForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchEmptyResults.js, invenio_administration/marshmallow_utils.py, invenio_administration/menu/menu.py, invenio_administration/views/base.py, invenio_administration/views/dashboard.py
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> I18n Translations Backport

.github/workflows/pypi-publish.yml, .github/workflows/tests.yml, invenio_administration/admin.py, invenio_administration/assets/semantic-ui/js/invenio_administration/package.json, invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModal.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/ActionForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js, invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchEmptyResults.js, invenio_administration/marshmallow_utils.py, invenio_administration/menu/menu.py, invenio_administration/views/base.py, invenio_administration/views/dashboard.py
Mark missing strings for:
* /admin.py
* /assets/semantic-ui/js/invenio_administration/src/actions/DeleteModal.js
* /assets/semantic-ui/js/invenio_administration/src/formik/ActionForm.js
* /assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js
* /assets/semantic-ui/js/invenio_administration/src/search/SearchEmptyResults.js
* /marshmallow_utils.py
* /menu/menu.py
* /views/base.py
* /views/dashboard.py
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend** …
=> Backport-from-maint-2.x

setup.cfg
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> fix: include invenio-i18n dependency
