inveniosoftware/invenio-administration

- .eslintrc.yml
- invenio_administration/assets/semantic-ui/js/invenio_administration/theme.js
- run-js-linter.sh
- setup.cfg
closes https://github.com/inveniosoftware/invenio-administration/issues/25
Bumped `invenio-vocabularies` to ƒix conflicts with `invenio-rdm-records` [0.36.0 release](https://github.com/inveniosoftware/invenio-rdm-records/commit/f8fd99726e4dacb638b5dded764f32828c3e729e)
`invenio-vocabularies` 0.12.0 release can be found [here](https://github.com/inveniosoftware/invenio-vocabularies/commit/200a5690fbccb17f7399eeb6e883b8484b606383) and does not seem to have breaking changes for `invenio-administration`
- Bumped `invenio-vocabularies` version.
- Changed `eslint` parser to match `eslint-config-invenio` after this [change](https://github.com/inveniosoftware/eslint-config-invenio/commit/9a115a061dc6984f77237ba600dcc586664d6d93). Tests for `eslint`were failing otherwise, as the `babel-eslint` …
> global: bumped invenio-vocabularies

- invenio_administration/admin.py
- invenio_administration/errors.py
- invenio_administration/ext.py
- invenio_administration/menu/menu.py
- invenio_administration/views/base.py
- tests/conftest.py
- tests/mock_module/__init__.py
- tests/mock_module/administration/__init__.py
- tests/mock_module/administration/mock.py
- tests/mock_module/config.py
- tests/mock_module/resource.py
- tests/test_admin_menu.py
- tests/test_base.py
closes #26 
- View `endpoint` is set to `name`, enforcing consistency and simplifying views management. 
- This prevents errors when the urls for the view functions are obtained (see flask [doc](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.url_for)) in scenarios where `name != endpoint` (e.g. `name = "My View" and endpoint = "myview"`)
- Added validation enforcing that view names must be unique (e.g. two views with the same name are not allowed). This is a direct consequence of the aforementioned change. It simplifies the management of views as views with the different names require that endpoints could differ from the names.
- Added subclass validation for Views, guaranteeing that only subclasses of `AdminBaseView` are registered.
- Added `menu_label` attribute. 
- Allows …
> base: forced endpoint to views name

- invenio_administration/admin.py
- invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Actions.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Create.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/actions/CustomResourceActions.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Delete.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Edit.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/actions/index.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/api/actions.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/api/config.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/api/routes.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/routes.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchBarElement.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultItem.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultOptions.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/search/SearchResultsContainer.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/search/search.js
- invenio_administration/views/base.py
- tests/mock_module/administration/mock.py
Some tests will still fail, as we have multiple "placeholders" in code that are simply waiting to be implemented. Namely errors like `React is defined but never used`, as we're yet not rendering any component. 
E.g. :https://github.com/inveniosoftware/invenio-administration/blob/f23bacffd5fac63f6b697eb1563150ed817a6ba2/invenio_administration/assets/semantic-ui/js/invenio_administration/actions/Edit.js#L1-L8
> eslint: fixing minor linting issues.

- invenio_administration/config.py
- invenio_administration/menu/menu.py
- invenio_administration/templates/semantic-ui/invenio_administration/sidebar/sidenav.html
- invenio_administration/views/base.py
- invenio_administration/views/dashboard.py
- setup.cfg
added a configuration variable that can hold templates that can then be declared for views, the menu item of that view will be displayed with that icon.
closes https://github.com/inveniosoftware/invenio-administration/issues/22
> menu: add possibility to define icons for menu items

- invenio_administration/templates/semantic-ui/invenio_administration/macros.html
Adds a bit more spacing between the back-button and the headline.
> details back-button: add more spacing to headline

- invenio_administration/assets/semantic-ui/js/invenio_administration/src/components/DateFormatter.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/GenerateForm.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResultsContainer.js
* display empty value if field is None
* add possibility to prefill fields with default value
* add render of checkbox and dropdown fields
* closes https://github.com/inveniosoftware/invenio-banners/issues/10
* requires: https://github.com/inveniosoftware/react-invenio-forms/pull/189
Previews:
1. End DateTime is None - display empty value
2.
2.1 Render checkbox (Active) and dropdown (Category) fields.
2.2 Message field - text area
2.3 Prefill Start DateTime with default value (utcnow) and Active with True
> forms: improve diversity of fields

- invenio_administration/assets/semantic-ui/js/invenio_administration/src/components/utils.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/details/AdminDetailsView.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/GenerateForm.js
* closes https://github.com/inveniosoftware/invenio-administration/issues/155
* requires https://github.com/inveniosoftware/invenio-rdm-records/pull/1193
Before: fields order in details, create and edit views is alphabetical
After: fields order corresponds to the one specified in [config](https://github.com/inveniosoftware/invenio-banners/blob/master/invenio_banners/administration/banners.py).
Details page:
Create page:
Edit page:
> global: fix fields sorting in details, create and edit views

- CHANGES.rst
- invenio_administration/__init__.py
- invenio_administration/errors.py
- invenio_administration/menu/menu.py
- setup.cfg
- NOTE: invenio-i18n has to be released first
> migrate: flask_babelex replaced by invenio_i18n

- invenio_administration/marshmallow_utils.py
The current user_administration fails because the marshmallow schema fails to convert to json, since it needs something for a field called `is_current_user` which maps to a method. This is a workaround. It should be better handled during ticket
https://github.com/inveniosoftware/invenio-administration/issues/174
It addresses https://github.com/inveniosoftware/invenio-app-rdm/issues/2232
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members) …
> Adding a mapping for the fields.Method

- invenio_administration/admin.py
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/Actions.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/ResourceActions.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/index.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/api/index.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/index.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchBulkActionContext.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResultItem.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/index.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/search.js
- invenio_administration/marshmallow_utils.py
- invenio_administration/views/base.py
- run-js-linter.sh
closes https://github.com/inveniosoftware/invenio-requests/issues/347
**Note**:
For user moderation we needed the actions to be faster to execute (e.g. we don't need a modal to accept/block). That's why I made the component `ResourceActions` overridable.
Please challenge the idea, it was the only one I was able to think of but it is by no means the best.
> wip: made resource actions overridable.

- invenio_administration/marshmallow_utils.py
- tests/test_marshmallow_utils.py
closes #190 
**Reminder**
2. You agree that you have the right to license your contribution under the …
> marshmallow_utils: include DynamicSanitizedHTML

- CHANGES.rst
- MANIFEST.in
- docs/conf.py
- invenio_administration/__init__.py
- invenio_administration/admin.py
- invenio_administration/errors.py
- invenio_administration/marshmallow_utils.py
- invenio_administration/menu/menu.py
- invenio_administration/views/base.py
- invenio_administration/webpack.py
- setup.cfg
- tests/test_marshmallow_utils.py
- installation: bump invenio-accounts
- relase: v2.0.0
> Bump invenio-accounts and release v2.0.0

- invenio_administration/templates/semantic-ui/invenio_administration/header/header_login.html
- invenio_administration/translations/messages.pot
This pull request fixes issue #200 - invenio-administration uses `url_for` for OAI-PMH server but does not depend on it. The proposed solution is just to remove the explicit menu link for the new oaipmh set. A new set can be created from within the oai listing panel the same way other objects are created: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/administration/views/oai.py
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/arch …
> Removed dependency on OAI-PMH, the menu should be inside the OAIPMH panel

- invenio_administration/views/base.py
To be able to have an AdminResourceListView after an AdminResourceListView we need to be able to define variable api_endpoints. This enables us to do so while keeping backwards compatibility.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contri …
> accept kwargs to be passed to get_api_endpoint

- invenio_administration/assets/semantic-ui/js/invenio_administration/src/components/Formatter.js
The only time `fieldSchema` is only used as follows:
```js
if (fieldSchema?.escape) {
return <div dangerouslySetInnerHTML={{ __html: value }} />;
}
```
and when `fieldSchema` was committed:
https://github.com/inveniosoftware/invenio-administration/commit/e30d0f81886c5018ed613f6a1ec6a9cd019dadbf
the other reference to this function was not updated:
https://github.com/inveniosoftware/invenio-administration/blob/main/invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchResultItem.js#L68-L80
Therefore I think we can just say it's not required as the implementation accounts for it not having the key
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to …
> js: remove required restriction on fieldSchema

- invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/GenerateForm.js
Closes https://github.com/inveniosoftware/invenio-jobs/issues/23
- Right now using TextAreaField for the json object so need to transform it accordingly before rendering in the form and submitting 
- Will introduce a separate component for json specifically in future
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> form: added support for json fields

- invenio_administration/assets/semantic-ui/js/invenio_administration/src/components/BoolFormatter.js
`value` is used as a boolean, and therefore all the uses of this in the codebase pass a boolean test as value. I think value isn't a great name for this, but at least we should fix the expected type
```js
class BoolFormatter extends React.Component {
render() {
const { value, icon, color, tooltip } = this.props;
if (!value) {
return null;
}
return <Icon title={tooltip} name={icon} color={color} />;
}
}
```
There is a warning from eslint that we should provide a default value for the `tooltip` and looking at the repository, this icon is used to mean a variety of things such as activated, success, verified, confirmed, etc. As such I don't think we can define a sensible default value for `tooltip`
Ticks in …
> bug: fix type for BoolFormatter value

- .github/workflows/pypi-publish.yml
- CHANGES.rst
- invenio_administration/__init__.py
- setup.cfg
- tests/conftest.py
- setup: bump major dependencies
- relase: v3.0.0
> bump major

- invenio_administration/admin.py
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/actions/DeleteModal.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/ActionForm.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/AdminForm.js
- invenio_administration/assets/semantic-ui/js/invenio_administration/src/search/SearchEmptyResults.js
- invenio_administration/marshmallow_utils.py
- invenio_administration/menu/menu.py
- invenio_administration/views/base.py
- invenio_administration/views/dashboard.py
> Fix-translations

- invenio_administration/webpack.py
* invenio-administration depends on TinyMCE
* Added it as a webpack dependency
See: https://github.com/inveniosoftware/invenio-app-rdm/pull/3126
closes: https://github.com/CERNDocumentServer/cds-ils/issues/1006
> theme: move TinyMCE from invenio-app-rdm to invenio-administration

- invenio_administration/templates/semantic-ui/invenio_administration/index.html
Invenio-ILS now also uses invenio-administration and requires the welcome message to not be RDM specific.
closes: https://github.com/CERNDocumentServer/cds-ils/issues/102
> index: change welcome message to be non RDM-specific
